social_django/social/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import ObtainAuthToken 
from .views.profile_views import ProfileViewSet, ProfileDetailViewSet
from .views.category_views import CategoryViewSet, CategoryDetailViewSet
from .views.post_views import PostViewSet, PostDetailViewSet
from .views.comment_views import CommentViewSet, CommentDetailViewSet

router = DefaultRouter()
router.register(r'perfil', ProfileViewSet, basename='perfil-api')
router.register(r'perfil-detalle', ProfileDetailViewSet, basename='perfil-detalle-api')
router.register(r'categoria', CategoryViewSet, basename='categoria-api')
router.register(r'categoria-detalle', CategoryDetailViewSet, basename='categoria-detalle-api')
router.register(r'posteo', PostViewSet, basename='posteo-api')
router.register(r'posteo-detalle', PostDetailViewSet, basename='posteo-detalle-api')
router.register(r'comentarios', CommentViewSet, basename='commentario-api')
router.register(r'comentarios-detalle', CommentDetailViewSet, basename='commentario-detalle-api')


urlpatterns = [
    path('v1/', include(router.urls)),
    path('token/', ObtainAuthToken.as_view(), name = 'token-api')
]

social_django/social/urls.py
from django.urls import path

from social import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'blog'


urlpatterns = [
    path('', views.feed, name='feed'),
    path('profile/', views.profile, name='profile'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    
    path('login/',LoginView.as_view(template_name='blog/login.html'),name='login'),
    path('logout/',LogoutView.as_view(template_name='blog/logout.html'),name='logout'),
    path('post/', views.post, name='post'),
    

    path('categories', views.CategoryListView.as_view(), name='category_list'),
    path('categories/<int:category_id>/detail', views.CategoryDetailView.as_view(), name='category_detail'),
    path('categories/create/', views.CreateCategoryView.as_view(), name='create_category'),
    path('categories/<int:category_id>/update/', views.UpdateCategoryView.as_view(), name='update_category'),
    path('categories/<int:category_id>/delete/', views.DeleteCategoryView.as_view(), name='delete_category'),

   
]    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # subir archivos estaticos por usuario

social_django/social/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.db.models.signals import post_save
from simple_history.models import HistoricalRecords

class Profile(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=False, null=False)
    image = models.ImageField(default='batman.png')
    historical = HistoricalRecords()

    def __str__(self):
        return f'perfil de {self.user.username}'
    
class Post(models.Model):
    user = models.ForeignKey(get_user_model() , on_delete=models.CASCADE , related_name='posts', blank=False, null=False)
    timestamp = models.DateTimeField(default=timezone.now)
    content = models.TextField()

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f'{self.user.username}: {self.content}'
    

social_django/social/models/category.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=200)

    class Meta:
        verbose_name = ("Categoria")
        verbose_name_plural=("Categorias")


    def __str__(self):
        return self.name
    
    

social_django/social/models/comment.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model


class Comment(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)  # Opcional, si deseas vincular el autor a un usuario registrado.
    content = models.TextField(blank=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
   


    class Meta:
        verbose_name = ("Comentario")
        verbose_name_plural = ("Comentarios")


    def __str__(self):
        return f"Comment by {self.author} on {self.post.content}"
    

    

social_django/social/models/post.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.db.models.signals import post_save


class Post(models.Model):
    user = models.ForeignKey(get_user_model() , on_delete=models.CASCADE , related_name='posts', blank=False, null=False)
    timestamp = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, blank=True, null=True)
    tags = models.ManyToManyField('Tag',blank=True)
    content = models.TextField()

    class Meta:
        ordering = ['-timestamp']
        verbose_name = ("Posteo")
        verbose_name_plural=("Posteos")

    def __str__(self):
        return f'{self.user.username}: {self.content}'
    

social_django/social/models/profile.py
from django.db import models
from django.contrib.auth import get_user_model
from simple_history.models import HistoricalRecords

class Profile(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, blank=False, null=False)
    image = models.ImageField(default='batman.png')
    historical = HistoricalRecords()

    class Meta:
        verbose_name = ("Perfil")
        verbose_name_plural=("Perfiles")

    def __str__(self):
        return f'perfil de {self.user.username}'
    

social_django/social/models/tags.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=100)


    class Meta:
        verbose_name = ("Tag")
        verbose_name_plural=("Tags")


    def __str__(self):
        return self.name

social_django/social/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Post

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirma Contraseña', widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        help_texts = {k:"" for k in fields}


class PostForm(forms.ModelForm):
    tittle = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':1,'placeholder': 'nombre publicacion...'}),required = True)
    content = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':2,'placeholder': 'que quieres contar...'}),required = True)

    class Meta:
        model = Post
        fields = ['tittle','content']

social_django/social/forms/category_forms.py
from django import forms
from ..models import Category

class CategoryForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols': 15}),label='Descripción')  


    class Meta:
        model = Category
        fields = ['name','description']

        labels = {
                'name': 'Nombre',  
            }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class':'form-control','placeholder':'Titulo de categoria'})
        self.fields['description'].widget.attrs.update({'class':'form-control form-control-lg','placeholder':'Contenido'})
        

social_django/social/forms/post_forms.py
from django import forms
from social.models import Post

class PostForm(forms.ModelForm):
    tittle = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':1,'placeholder': 'nombre publicacion...'}),required = True)
    content = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':2,'placeholder': 'que quieres contar...'}),required = True)

    class Meta:
        model = Post
        fields = ['tittle','content']

social_django/social/forms/user_forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirma Contraseña', widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        help_texts = {k:"" for k in fields}

social_django/social/api/views/category_views.py
from rest_framework import viewsets, permissions
from rest_framework.viewsets import ModelViewSet
from social.models import Category
from social.api.serializers import CategorySerializer


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = [permissions.IsAuthenticated]


class CategoryDetailViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = [permissions.IsAuthenticated]

social_django/social/api/views/comment_views.py
from rest_framework import viewsets, permissions
from rest_framework.viewsets import ModelViewSet
from social.models import Comment
from social.api.serializers import CommentSerializer


class CommentViewSet(ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [permissions.IsAuthenticated]


class CommentDetailViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [permissions.IsAuthenticated]

social_django/social/api/views/post_views.py
from rest_framework import viewsets,permissions,status
from rest_framework.viewsets import ModelViewSet
from rest_framework.response import Response
from social.models import Post
from social.api.serializers import PostSerializer


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticated]
   
class PostDetailViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticated]
 

social_django/social/api/views/profile_views.py
from rest_framework import viewsets, permissions
from rest_framework.viewsets import ModelViewSet
from social.models import Profile
from social.api.serializers import ProfileSerializer


class ProfileViewSet(viewsets.ModelViewSet):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer
    permission_classes = [permissions.IsAuthenticated]


class ProfileDetailViewSet(viewsets.ModelViewSet):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer
    permission_classes = [permissions.IsAuthenticated]

social_django/social/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import UserRegisterForm , PostForm
from django.contrib import messages
from django.contrib.auth import get_user_model 

def feed(request):
    posts = Post.objects.all()



    context = {'posts': posts}
    return render(request, 'blog/feed.html',context)


def register(request):              # registro
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request , f'Usuario {username} creado')
            return redirect('feed')
    else:
        form = UserRegisterForm()
    
    context = {'form' : form }
    return render (request,'blog/register.html', context)


def post(request):
    current_user = get_object_or_404(get_user_model(), pk=request.user.pk)
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user=current_user
            post.save()
            messages.success(request, 'Post enviado')
            return redirect('feed')
    else:
        form = PostForm()
    return render(request, 'blog/post.html', {'form': form})




def profile(request, username= None):
    current_user = request.user
    if username and username != current_user.username:
        user = get_user_model().objects.get(username=username)
        posts = user.posts.all()

    else:
        posts = current_user.posts.all()
        user = current_user
    return render (request, 'blog/profile.html',{'user':user, 'posts':post})

social_django/social/views/category_view.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from ..forms import CategoryForm
from ..models import Category


class CategoryListView(LoginRequiredMixin, View):
    template_name = 'blog/category/list.html'

    def get(self, request):
        categories = Category.objects.all()
        return render(request, self.template_name, {'categories': categories})


class CreateCategoryView(LoginRequiredMixin, View):
    template_name = 'blog/category/create_category.html'

    def get(self, request):
        form = CategoryForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = CategoryForm(request.POST)
        if form.is_valid():
            category_name = form.cleaned_data['name']
            if Category.objects.filter(name=category_name).exists():
                form.add_error('name','Ya existe una categoria con este nombre.')
            else:
                form.save()
                return redirect('blog:category_list')
        return render(request, self.template_name, {'form': form})


class UpdateCategoryView(LoginRequiredMixin, View):
    template_name = 'blog/category/update_category.html'

    def get(self, request, category_id):
        category = get_object_or_404(Category, id=category_id)
        form = CategoryForm(instance=category)
        return render(request, self.template_name, {'form': form, 'category': category})

    def post(self, request, category_id):
        category = get_object_or_404(Category, id=category_id)
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('blog:category_list')
        return render(request, self.template_name, {'form': form, 'category': category})


class DeleteCategoryView(LoginRequiredMixin, View):
    template_name = 'blog/category/delete_category.html'

    def get(self, request, category_id):
        category = get_object_or_404(Category, id=category_id)
        return render(request, self.template_name, {'category': category})

    def post(self, request, category_id):
        category = get_object_or_404(Category, id=category_id)
        category.delete()
        return redirect('blog:category_list')


class CategoryDetailView(LoginRequiredMixin, View):
    template_name = 'blog/category/detail.html'

    def get(self, request, category_id):
        category = get_object_or_404(Category, id=category_id)
        return render(request, self.template_name, {'category': category})

social_django/social/views/post_view.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import get_user_model 
from ..models import Post
from ..forms import UserRegisterForm , PostForm

def feed(request):
    posts = Post.objects.all()
    context = {'posts': posts}
    return render(request, 'blog/feed.html',context)


def register(request):              # registro
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request , f'Usuario {username} creado')
            return redirect('feed')
    else:
        form = UserRegisterForm()
    
    context = {'form' : form }
    return render (request,'blog/register.html', context)


def post(request):
    current_user = get_object_or_404(get_user_model(), pk=request.user.pk)
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user=current_user
            post.save()
            messages.success(request, 'Post enviado')
            return redirect('feed')
    else:
        form = PostForm()
    return render(request, 'blog/post.html', {'form': form})




def profile(request, username= None):
    current_user = request.user
    if username and username != current_user.username:
        user = get_user_model().objects.get(username=username)
        posts = user.posts.all()

    else:
        posts = current_user.posts.all()
        user = current_user
    return render (request, 'blog/profile.html',{'user':user, 'posts':post})

social_django/social/templates/blog/category/create_category.html
{% extends 'blog/layout.html' %}


{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Crear Categoría</h4>
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-info btn-block">Crear Categoría</button>
          </form>
          <a href="{% url 'blog:category_list' %}" class="btn btn-danger btn-block mt-3">Cancelar</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

social_django/social/templates/blog/category/detail.html
{% extends 'blog/layout.html' %}
{% block content %}

<div class="page-titles">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="javascript:void(0)">Blog</a></li>
    <li class="breadcrumb-item active"><a href="javascript:void(0)">Detalle Categorías</a></li>
  </ol>
</div>

<div class="d-flex justify-content-center align-items-center h-100">
  <div class="col-xl-8 col-lg-12 col-sm-12">
    <div class="card">
      <div class="text-center p-4 overlay-box">
        <div class="profile-photo">
          <img src="" width="100" class="img-fluid rounded-circle" alt="">
        </div>
        <h3 class="text-white mb-0 overflow-auto" style="max-height: 100px;">{{ category.name }}</h3>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item d-flex justify-content-between">
          <span class="mb-0">Descripción: </span>
        </li>
        <div class="text-center">
          <h2 class="text-muted mb-0"
            style="max-height: 200px; overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 6; -webkit-box-orient: vertical;">
            {{ category.description }}</h2>
        </div>
      </ul>


      <div class="card-footer border-0 mt-0">
        <a href="{% url 'blog:category_list' %}" class="btn btn-secondary btn-lg btn-block">
          <span class="me-2"><i class="fa fa-reply"></i> ㅤ</span>Volver a Categorías
        </a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

social_django/social/templates/blog/category/list.html
{% extends 'blog/layout.html' %}

{% block content %}

<div class="page-titles text-center">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:void(0)">Blog</a></li>
        <li class="breadcrumb-item active"><a href="javascript:void(0)">Categorias</a></li>
    </ol>
</div>

<div class="text-center mb-4">
    <a href="{% url 'blog:create_category' %}" class="btn btn-rounded btn-info">
        <button type="submit" class="btn light btn-danger">Añadir categoria</button>
    </a>
</div>

<div class="col-lg-12">
    <div class="card">
        <div class="card-header">
            <h2 class="card-title">Listado de Categorías</h2>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-striped verticle-middle table-responsive-sm">
                    <tbody>
                        {% for category in categories %}
                        <tr>
                            <td>
                                <h3><a class="d-flex align-items-center"
                                        href="{% url 'blog:category_detail' category.id %}" style="font-size: 1.5rem;">
                                        {{ category.name }}
                                    </a></h3>
                            </td>
                            <td>
                                <div class="d-flex">
                                    <a href="{% url 'blog:update_category' category.id %}"
                                        class="btn btn-primary shadow btn-sm sharp me-2">
                                        <i class="fa fa-pencil"></i> Editar
                                    </a>
                                    <form method="post" action="{% url 'blog:delete_category' category.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn light btn-danger">Eliminar</button>
                                    </form>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

social_django/social/templates/blog/category/update_category.html
{% extends 'blog/layout.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-header">
          <h2 class="card-title">Editar Categoría</h2>
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary btn-block">Guardar Cambios</button>
          </form>
          <a href="{% url 'blog:category_list' %}" class="btn btn-danger btn-block mt-3">Cancelar</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}